### ISSUE TITLE
default Image in profile picture 

### ISSUE THREAD

**Issue by 90301** [90301/Crescent-CRM-V#151]
![image](https://cloud.githubusercontent.com/assets/6025683/22843928/b9309a54-efa9-11e6-9999-a23d3aeac9ef.png)

**Comment by FfGingaNinja** [comment]
So we need to have the default image stored in the directory 
![defaultpicture](https://cloud.githubusercontent.com/assets/21223293/22850853/6ea39df2-efdf-11e6-8fa9-a47ecc9b45d7.jpg)

**Comment by FfGingaNinja** [comment]
Currently have a temp fix, but will add to themes so that the image will be easier to store/access.
