### ISSUE TITLE
Image glitch

### ISSUE THREAD

**Issue by 90301** [90301/Crescent-CRM-V#163]
Uploaded a PNG, now the colors are all kinds of messed up.

This is the image that glitched.
![37zm2vh](https://cloud.githubusercontent.com/assets/6025683/23387315/c1171698-fd29-11e6-934d-d107d78c2ad2.png)

![image](https://cloud.githubusercontent.com/assets/6025683/23387294/b0b63be4-fd29-11e6-895a-de0df0c99c31.png)

**Comment by FfGingaNinja** [comment]
Fixed and comitted.

**Comment by FfGingaNinja** [comment]
Good catch by the way!
