### ISSUE TITLE
Move upload image to be beside profile picture.

### ISSUE THREAD

**Issue by 90301** [90301/Crescent-CRM-V#167]
the client editor is getting really vertical, we need to push the upload image widget up to be in the same area as the profile picture.

**Comment by FfGingaNinja** [comment]
You think it looks better beside the name? Or is it to allow it to not take up so much space? I can add the name label and the picture to a horizontal layout and make this happen somewhat easily.

**Comment by 90301** [comment]
Give it a shot, though I just wanted the profile picture and the upload widget in the same horrizontal layout.
