### ISSUE TITLE
Rename CRM to Clients

### ISSUE THREAD

**Issue by 90301** [90301/Crescent-CRM-V#168]
Clients seems to be a better term for those unfirmilar with "crm." Open to other names.

**Comment by FfGingaNinja** [comment]
Yes, it would be easier to understand for the users

**Comment by FfGingaNinja** [comment]
Or maybe "Client Database" depending on how much text we want to allow in the button on the nav bar.

**Comment by troywingert21** [comment]
People who are in the market for a software like this will find CRM in their first google search. There is no other acronym for a customer relations software. If a client types "customer management software" into google then nearly every link has CRM in it with a description of the acronym. 

I think it's fine how it is, CRM is the sole universally used acronym.

**Comment by 90301** [comment]
Changed to clients in V 1.33
