### ISSUE TITLE
Inventory section bug

### ISSUE THREAD

**Issue by discgolfer78** [90301/Crescent-CRM-V#174]
After changing item stock from 0 to 1(or any number) the number then goes back to zero if you logout. Item Stock amount number needs to be persistent and not change upon logout

**Comment by 90301** [comment]
Did you update the table?

**Comment by 90301** [comment]
Attempted to recreate. failed to get a bug. You must click the update button. I agree this is not ideal.

**Comment by 90301** [comment]
Ticket created for this purpose.

#178
