### ISSUE TITLE
Make it fit on a 15" screen

### ISSUE THREAD

**Issue by josemvidal** [90301/Crescent-CRM-V#186]
<img width="1678" alt="cursor_and_styleconnect_net_8080_crescent-crm-vaadin-maven___mainapp_ _and_inbox__3_messages_-_connection_logging_enabled_" src="https://cloud.githubusercontent.com/assets/228704/23611447/6e8d0218-0245-11e7-87e1-1a6f7606560d.png">

**Comment by FfGingaNinja** [comment]
http://stackoverflow.com/questions/3680221/how-can-i-get-screen-resolution-in-java
great source for getting screen size which should be easy to add.

**Comment by 90301** [comment]
Screen resolution to add support for? I just don't see how we can make it fit on 1376 x 768 without support for using much smaller fonts (essentially a complete theme override).

Also, the above link does not apply. We are not getting the screen resolution of the SERVER.

I've tried cracking this nut before, we need the screen resolution in vaadin, but that's not easy to get.

**Comment by 90301** [comment]
https://vaadin.com/wiki/-/wiki/Main/Valo+theme+-+Getting+started

This controls the font size variables, but we need to over-ride it only when a certain condition is met.

As of this time, I don't know how we do that.

**Comment by 90301** [comment]
Small Visual Mode Added, with frozen columns. This setting is found in the user editor.
