### ISSUE TITLE
Better Labels on CRM screen?

### ISSUE THREAD

**Issue by josemvidal** [90301/Crescent-CRM-V#188]
<img width="1236" alt="styleconnect_net_8080_crescent-crm-vaadin-maven___mainapp_ _and_inbox__3_messages_-_connection_logging_enabled_" src="https://cloud.githubusercontent.com/assets/228704/23612203/73f990ec-0248-11e7-833a-7298608bf4bc.png">

- [x]  Nav Bar Updated

- [x] Client Grid Names

- [ ]  Better Date Format

**Comment by 90301** [comment]
.
