### ISSUE TITLE
Upgrade to Vaadin 8

### ISSUE THREAD

**Issue by 90301** [90301/Crescent-CRM-V#224]
All code must be merged before the upgrade. (Whoops)

- [ ] upgrade UI

- [ ] upgrade grid

- [ ] upgrade comboboxes in crmui to use objects, not strings

**Comment by 90301** [comment]
https://iniy.org/?p=662

**Comment by 90301** [comment]
https://github.com/vaadin/valo-demo/blob/master/pom.xml

**Comment by FfGingaNinja** [comment]
hmmm
where to start

**Comment by 90301** [comment]
Pull the branch. For some reason it's using the default widgetset, somehow we have to change that to the compatibility widget set, or change how it compiles.

**Comment by 90301** [comment]
https://vaadin.com/forum#!/thread/230259

**Comment by 90301** [comment]
Major Move made, everything else will be separate tickets.
