### ISSUE TITLE
Error Updating Location Proximity

### ISSUE THREAD

**Issue by forember** [90301/Crescent-CRM-V#237]
![updateproximitynull](https://cloud.githubusercontent.com/assets/6026457/24431389/9b81dd60-13e9-11e7-911d-ce7774ea1ccb.png)

Got a null pointer on updating proximity for location "Actually Nowhere."

I then reselected "Actually Nowhere":

![updateproximitynulls](https://cloud.githubusercontent.com/assets/6026457/24431475/1630ab54-13ea-11e7-82d2-68bbbccb2b1b.png)

The first error was at Location.java:88 from CategoryEditorView.java:433, and the second was at Location.java:88 from CategoryEditorView.java:532.

**Comment by 90301** [comment]
![image](https://cloud.githubusercontent.com/assets/6025683/24467742/b2084afc-1483-11e7-80ec-c49678704798.png)
either the user data holder is null, or its unable to find the location. neither error condition is handled. both must be handled. Also we need to figure out why the userDataHolder is null, if thats the case.

**Comment by 90301** [comment]
![image](https://cloud.githubusercontent.com/assets/6025683/24468134/4785ced2-1485-11e7-982a-fbc09ead781b.png)
similar issue occurred on selection.

**Comment by 90301** [comment]
The userDataHolder was not set, I set it now when it's loaded. Will investigate further into this before closing.
Technically there may be a deeper issue then what I fixed.

**Comment by 90301** [comment]
seems to be fixed.
