### ISSUE TITLE
Add a Filter Button

### ISSUE THREAD

**Issue by forember** [90301/Crescent-CRM-V#241]
I know you can hit enter or just click off to do the filter, but this was actually non-obvious to me the first time. Heck, the button doesn't even have to do anything, as clicking it will move focus, performing the filter.

![filterbutton](https://cloud.githubusercontent.com/assets/6026457/24432367/9eddfcae-13ef-11e7-9a08-560d27f88a40.png)

**Comment by 90301** [comment]
Filter button added.
