### ISSUE TITLE
Debugging Button is not available on server

### ISSUE THREAD

**Issue by FfGingaNinja** [90301/Crescent-CRM-V#247]
![image](https://cloud.githubusercontent.com/assets/21223293/24531293/dde2a796-1585-11e7-9dd8-e7600c699a56.png)

**Comment by 90301** [comment]
must have dev mode set to true. must be an admin.

**Comment by 90301** [comment]
if both conditions are met, and the issue persists, comment as such. if it works, please close the issue.

**Comment by FfGingaNinja** [comment]
This was off of the server http://styleconnect.net:8080/Crescent-CRM-Vaadin-Maven/%23!Login#!Login

**Comment by FfGingaNinja** [comment]
![image](https://cloud.githubusercontent.com/assets/21223293/24532154/33fedf22-158c-11e7-8a34-74fb8345cfe9.png)

Logging in

**Comment by FfGingaNinja** [comment]
![image](https://cloud.githubusercontent.com/assets/21223293/24532159/4125528a-158c-11e7-86b6-222fca11d7b6.png)
After logging in

**Comment by 90301** [comment]
oh, well yeah. we turn off dev mode on the server. that way we don't waste ram / system resources doing unnecessary actions.
