### ISSUE TITLE
Fix the backups/restores

### ISSUE THREAD

**Issue by discgolfer78** [90301/Crescent-CRM-V#29]
Restoring not working as inspected, backing up seems to work as expected. Further investigation is required.

**Comment by 90301** [comment]
//TODO: change this code to work by splitting the string on the END_OF_LINE delimiter

**Comment by 90301** [comment]
Backup manager, restore function

**Comment by 90301** [comment]
MaxObject.loadFromCSV()
Loading: lastUpdated from csv with value: 2016-09-02 01:37:34.0
loaded ref: null

It may have something to do with not having a conversion for the date.

**Comment by 90301** [comment]
Added support for dates, made the simple date format a constant.
added client date to the table.
Appears to function correctly!
