### ISSUE TITLE
Docker Container Deployment

### ISSUE THREAD

**Issue by 90301** [90301/Crescent-CRM-V#31]
Look into making a docker container for this Dev environment. 

https://www.docker.com/

**Comment by 90301** [comment]
https://docs.docker.com/engine/tutorials/dockerimages/

**Comment by 90301** [comment]
Full Docker talk:
https://www.youtube.com/watch?v=GWqA-S-faAs
Docker in Eclipse:
https://www.youtube.com/watch?v=oxlVasKGaYk

**Comment by FfGingaNinja** [comment]
This page gives you a lot of info on how to get Docker running and to add images.
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04
